[package]
name = "crow-provider-registry"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
crow-core.workspace = true
crow-provider-proxmox.workspace = true
crow-db.workspace = true

serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
