use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::net::IpAddr;

// --- VM ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmSpec {
    pub name: String,
    pub cpu: u32,
    pub memory_mib: u64,
    pub disk_gib: u64,
    pub image: String,
    pub ip: Option<IpAddr>,
    pub cloud_init: Option<CloudInitConfig>,
    pub network_ref: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CloudInitConfig {
    pub hostname: String,
    pub user_data: Option<String>,
    pub network_config: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VmHandle {
    pub provider_type: String,
    pub provider_id: String,
    pub ip: Option<IpAddr>,
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum VmStatus {
    Running,
    Stopped,
    Starting,
    Stopping,
    Error(String),
    Unknown,
}

// --- K8sCluster ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct K8sClusterHandle {
    pub control_plane: VmHandle,
    pub workers: Vec<VmHandle>,
    /// Pre-shared K3s cluster token generated by crowCloud (not left to
    /// K3s's own auto-generation) so worker cloud-init can join without
    /// ever needing to read anything back from the control plane first.
    pub cluster_token: String,
    /// Per-cluster secret the control plane's cloud-init presents when it
    /// calls back to crow-api to report the cluster is up and hand over the
    /// kubeconfig — authenticates that callback without a user JWT, since
    /// the caller is a VM, not a logged-in user.
    pub bootstrap_secret: String,
    /// Set once the control plane's callback has arrived.
    pub kubeconfig: Option<String>,
    /// Stamped at `provision()` time — the bootstrap-timeout check in
    /// `reconcile()` compares against this rather than sitting at
    /// `Bootstrapping` forever if the callback never arrives.
    pub provisioned_at: DateTime<Utc>,
}

// --- Volume ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VolumeSpec {
    pub name: String,
    pub size_gib: u64,
    pub storage_pool: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VolumeHandle {
    pub provider_type: String,
    pub provider_id: String,
}

// --- Network ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkSpec {
    pub name: String,
    pub cidr: Option<String>,
    pub vlan_id: Option<u16>,
    pub bridge: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NetworkHandle {
    pub provider_type: String,
    pub provider_id: String,
}

// --- Expose ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HttpExposeSpec {
    pub domain: String,
    pub target_ip: IpAddr,
    pub target_port: u16,
    pub tls: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TcpExposeSpec {
    pub target_ip: IpAddr,
    pub target_port: u16,
    pub public_port: u16,
    pub protocol: Protocol,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Protocol {
    Tcp,
    Udp,
    TcpUdp,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExposeHandle {
    pub provider_id: String,
    pub domain: Option<String>,
    pub public_port: Option<u16>,
}

// --- TLS ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CertHandle {
    pub domain: String,
    pub provider_id: String,
    pub expiry: DateTime<Utc>,
}

// --- DNS ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DnsRecordSpec {
    pub name: String,
    pub record_type: DnsRecordType,
    pub value: String,
    pub ttl: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DnsRecordType {
    A,
    Aaaa,
    Cname,
    Txt,
    Mx,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DnsRecordHandle {
    pub provider_id: String,
    pub zone_id: Option<String>,
    pub name: String,
    pub record_type: DnsRecordType,
}

// --- Resource ---

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResourceHandle {
    pub resource_type: String,
    pub data: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ResourcePhase {
    Pending,
    ProvisioningInfra,
    Bootstrapping,
    HealthChecking,
    Ready,
    Degraded(String),
    Scaling,
    Upgrading,
    Deleting,
    Deleted,
    Failed(String),
}

impl std::fmt::Display for ResourcePhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "Pending"),
            Self::ProvisioningInfra => write!(f, "ProvisioningInfra"),
            Self::Bootstrapping => write!(f, "Bootstrapping"),
            Self::HealthChecking => write!(f, "HealthChecking"),
            Self::Ready => write!(f, "Ready"),
            Self::Degraded(msg) => write!(f, "Degraded: {msg}"),
            Self::Scaling => write!(f, "Scaling"),
            Self::Upgrading => write!(f, "Upgrading"),
            Self::Deleting => write!(f, "Deleting"),
            Self::Deleted => write!(f, "Deleted"),
            Self::Failed(msg) => write!(f, "Failed: {msg}"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Endpoint {
    pub name: String,
    pub url: String,
    pub description: Option<String>,
}
