apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crowcloud.fullname" . }}-api
  labels:
    {{- include "crowcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crowcloud.fullname" . }}-api
subjects:
  - kind: ServiceAccount
    name: {{ include "crowcloud.fullname" . }}-api
    namespace: {{ .Release.Namespace }}
